//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab7b.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TelephoneNote", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TelephoneNote : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetDictResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDict", ReplyAction="*")]
        Lab7b.ServiceReference1.GetDictResponse GetDict(Lab7b.ServiceReference1.GetDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab7b.ServiceReference1.GetDictResponse> GetDictAsync(Lab7b.ServiceReference1.GetDictRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDict", ReplyAction="*")]
        Lab7b.ServiceReference1.AddDictResponse AddDict(Lab7b.ServiceReference1.AddDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab7b.ServiceReference1.AddDictResponse> AddDictAsync(Lab7b.ServiceReference1.AddDictRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdDict", ReplyAction="*")]
        Lab7b.ServiceReference1.UpdDictResponse UpdDict(Lab7b.ServiceReference1.UpdDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab7b.ServiceReference1.UpdDictResponse> UpdDictAsync(Lab7b.ServiceReference1.UpdDictRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelDict", ReplyAction="*")]
        Lab7b.ServiceReference1.DelDictResponse DelDict(Lab7b.ServiceReference1.DelDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab7b.ServiceReference1.DelDictResponse> DelDictAsync(Lab7b.ServiceReference1.DelDictRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDict", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference1.GetDictRequestBody Body;
        
        public GetDictRequest() {
        }
        
        public GetDictRequest(Lab7b.ServiceReference1.GetDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDictRequestBody {
        
        public GetDictRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference1.GetDictResponseBody Body;
        
        public GetDictResponse() {
        }
        
        public GetDictResponse(Lab7b.ServiceReference1.GetDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab7b.ServiceReference1.TelephoneNote[] GetDictResult;
        
        public GetDictResponseBody() {
        }
        
        public GetDictResponseBody(Lab7b.ServiceReference1.TelephoneNote[] GetDictResult) {
            this.GetDictResult = GetDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDict", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference1.AddDictRequestBody Body;
        
        public AddDictRequest() {
        }
        
        public AddDictRequest(Lab7b.ServiceReference1.AddDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phone;
        
        public AddDictRequestBody() {
        }
        
        public AddDictRequestBody(string name, string phone) {
            this.name = name;
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference1.AddDictResponseBody Body;
        
        public AddDictResponse() {
        }
        
        public AddDictResponse(Lab7b.ServiceReference1.AddDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddDictResult;
        
        public AddDictResponseBody() {
        }
        
        public AddDictResponseBody(string AddDictResult) {
            this.AddDictResult = AddDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDict", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference1.UpdDictRequestBody Body;
        
        public UpdDictRequest() {
        }
        
        public UpdDictRequest(Lab7b.ServiceReference1.UpdDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phone;
        
        public UpdDictRequestBody() {
        }
        
        public UpdDictRequestBody(string name, string phone) {
            this.name = name;
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference1.UpdDictResponseBody Body;
        
        public UpdDictResponse() {
        }
        
        public UpdDictResponse(Lab7b.ServiceReference1.UpdDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdDictResult;
        
        public UpdDictResponseBody() {
        }
        
        public UpdDictResponseBody(string UpdDictResult) {
            this.UpdDictResult = UpdDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelDict", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference1.DelDictRequestBody Body;
        
        public DelDictRequest() {
        }
        
        public DelDictRequest(Lab7b.ServiceReference1.DelDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public DelDictRequestBody() {
        }
        
        public DelDictRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference1.DelDictResponseBody Body;
        
        public DelDictResponse() {
        }
        
        public DelDictResponse(Lab7b.ServiceReference1.DelDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DelDictResult;
        
        public DelDictResponseBody() {
        }
        
        public DelDictResponseBody(string DelDictResult) {
            this.DelDictResult = DelDictResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Lab7b.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Lab7b.ServiceReference1.WebServiceSoap>, Lab7b.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7b.ServiceReference1.GetDictResponse Lab7b.ServiceReference1.WebServiceSoap.GetDict(Lab7b.ServiceReference1.GetDictRequest request) {
            return base.Channel.GetDict(request);
        }
        
        public Lab7b.ServiceReference1.TelephoneNote[] GetDict() {
            Lab7b.ServiceReference1.GetDictRequest inValue = new Lab7b.ServiceReference1.GetDictRequest();
            inValue.Body = new Lab7b.ServiceReference1.GetDictRequestBody();
            Lab7b.ServiceReference1.GetDictResponse retVal = ((Lab7b.ServiceReference1.WebServiceSoap)(this)).GetDict(inValue);
            return retVal.Body.GetDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab7b.ServiceReference1.GetDictResponse> Lab7b.ServiceReference1.WebServiceSoap.GetDictAsync(Lab7b.ServiceReference1.GetDictRequest request) {
            return base.Channel.GetDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab7b.ServiceReference1.GetDictResponse> GetDictAsync() {
            Lab7b.ServiceReference1.GetDictRequest inValue = new Lab7b.ServiceReference1.GetDictRequest();
            inValue.Body = new Lab7b.ServiceReference1.GetDictRequestBody();
            return ((Lab7b.ServiceReference1.WebServiceSoap)(this)).GetDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7b.ServiceReference1.AddDictResponse Lab7b.ServiceReference1.WebServiceSoap.AddDict(Lab7b.ServiceReference1.AddDictRequest request) {
            return base.Channel.AddDict(request);
        }
        
        public string AddDict(string name, string phone) {
            Lab7b.ServiceReference1.AddDictRequest inValue = new Lab7b.ServiceReference1.AddDictRequest();
            inValue.Body = new Lab7b.ServiceReference1.AddDictRequestBody();
            inValue.Body.name = name;
            inValue.Body.phone = phone;
            Lab7b.ServiceReference1.AddDictResponse retVal = ((Lab7b.ServiceReference1.WebServiceSoap)(this)).AddDict(inValue);
            return retVal.Body.AddDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab7b.ServiceReference1.AddDictResponse> Lab7b.ServiceReference1.WebServiceSoap.AddDictAsync(Lab7b.ServiceReference1.AddDictRequest request) {
            return base.Channel.AddDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab7b.ServiceReference1.AddDictResponse> AddDictAsync(string name, string phone) {
            Lab7b.ServiceReference1.AddDictRequest inValue = new Lab7b.ServiceReference1.AddDictRequest();
            inValue.Body = new Lab7b.ServiceReference1.AddDictRequestBody();
            inValue.Body.name = name;
            inValue.Body.phone = phone;
            return ((Lab7b.ServiceReference1.WebServiceSoap)(this)).AddDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7b.ServiceReference1.UpdDictResponse Lab7b.ServiceReference1.WebServiceSoap.UpdDict(Lab7b.ServiceReference1.UpdDictRequest request) {
            return base.Channel.UpdDict(request);
        }
        
        public string UpdDict(string name, string phone) {
            Lab7b.ServiceReference1.UpdDictRequest inValue = new Lab7b.ServiceReference1.UpdDictRequest();
            inValue.Body = new Lab7b.ServiceReference1.UpdDictRequestBody();
            inValue.Body.name = name;
            inValue.Body.phone = phone;
            Lab7b.ServiceReference1.UpdDictResponse retVal = ((Lab7b.ServiceReference1.WebServiceSoap)(this)).UpdDict(inValue);
            return retVal.Body.UpdDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab7b.ServiceReference1.UpdDictResponse> Lab7b.ServiceReference1.WebServiceSoap.UpdDictAsync(Lab7b.ServiceReference1.UpdDictRequest request) {
            return base.Channel.UpdDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab7b.ServiceReference1.UpdDictResponse> UpdDictAsync(string name, string phone) {
            Lab7b.ServiceReference1.UpdDictRequest inValue = new Lab7b.ServiceReference1.UpdDictRequest();
            inValue.Body = new Lab7b.ServiceReference1.UpdDictRequestBody();
            inValue.Body.name = name;
            inValue.Body.phone = phone;
            return ((Lab7b.ServiceReference1.WebServiceSoap)(this)).UpdDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7b.ServiceReference1.DelDictResponse Lab7b.ServiceReference1.WebServiceSoap.DelDict(Lab7b.ServiceReference1.DelDictRequest request) {
            return base.Channel.DelDict(request);
        }
        
        public string DelDict(string name) {
            Lab7b.ServiceReference1.DelDictRequest inValue = new Lab7b.ServiceReference1.DelDictRequest();
            inValue.Body = new Lab7b.ServiceReference1.DelDictRequestBody();
            inValue.Body.name = name;
            Lab7b.ServiceReference1.DelDictResponse retVal = ((Lab7b.ServiceReference1.WebServiceSoap)(this)).DelDict(inValue);
            return retVal.Body.DelDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab7b.ServiceReference1.DelDictResponse> Lab7b.ServiceReference1.WebServiceSoap.DelDictAsync(Lab7b.ServiceReference1.DelDictRequest request) {
            return base.Channel.DelDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab7b.ServiceReference1.DelDictResponse> DelDictAsync(string name) {
            Lab7b.ServiceReference1.DelDictRequest inValue = new Lab7b.ServiceReference1.DelDictRequest();
            inValue.Body = new Lab7b.ServiceReference1.DelDictRequestBody();
            inValue.Body.name = name;
            return ((Lab7b.ServiceReference1.WebServiceSoap)(this)).DelDictAsync(inValue);
        }
    }
}
